### ISSUE TITLE
package.json says @sx-bet/sportx-js but documentation says @sportx-js/sportx-js 

### ISSUE THREAD

**Issue by thomkenn** [sx-bet/sportx-js#48]

**Comment by thomkenn** [comment]
When i run npm i @sx-bet/sportx-js I get an empty folder directory other then the readme. Doesnt seem like the latest build is working. and running on the old sportx-bet/sportx-js doesnt seem to recognize SX as an option 


![sportxjs](https://user-images.githubusercontent.com/11286095/188791654-dd81041d-5ead-46fa-9a79-1a756f0232aa.png)

**Comment by rohaanmalik** [comment]
updated the README.
